### ISSUE TITLE
analyze failed for node project: Illegal '//' in exclude path

### ISSUE THREAD

**Issue by viceice** [github/codeql-action#1017]
The analyze action fails since yesterday

```
Run github/codeql-action/analyze@4c10[2](https://github.com/renovatebot/renovate/runs/5828906475?check_suite_focus=true#step:5:2)1c5041fca602[3](https://github.com/renovatebot/renovate/runs/5828906475?check_suite_focus=true#step:5:3)82[4](https://github.com/renovatebot/renovate/runs/5828906475?check_suite_focus=true#step:5:4)e4[5](https://github.com/renovatebot/renovate/runs/5828906475?check_suite_focus=true#step:5:5)efb7f83178d52fe2
  with:
    output: ../results
    upload: true
    cleanup-level: brutal
    add-snippets: false
    skip-queries: false
    checkout_path: /home/runner/work/renovate/renovate
    upload-database: true
    wait-for-processing: false
    token: ***
    matrix: null
  env:
    CODEQL_ACTION_RUN_MODE: Action
    CODEQL_ACTION_VERSION: 1.1.[6](https://github.com/renovatebot/renovate/runs/5828906475?check_suite_focus=true#step:5:6)
    CODEQL_ACTION_FEATURE_SARIF_COMBINE: true
    CODEQL_ACTION_FEATURE_WILL_UPLOAD: true
    CODEQL_ACTION_ANALYSIS_KEY: .github/workflows/codeql-analysis.yml:CodeQL-Build
    CODEQL_WORKFLOW_STARTED_AT: 2022-04-05T06:45:54.201Z
    CODEQL_ACTION_FEATURE_MULTI_LANGUAGE: false
    CODEQL_ACTION_FEATURE_SANDWICH: false
    CODEQL_RAM: 5922
    CODEQL_THREADS: 2
/opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/codeql version --format=terse
2.8.3
Extracting javascript
  /opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/codeql database trace-command /home/runner/work/_temp/codeql_databases/javascript -- /opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/javascript/tools/autobuild.sh
  Running command in /home/runner/work/renovate/renovate: [/opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/javascript/tools/autobuild.sh]
  [2022-04-05 06:46:06] [build-stderr] Skipping path /home/runner/work/renovate/renovate/**/__fixtures__, which does not exist.
  [2022-04-05 06:46:06] [build-stderr] Illegal '//' in exclude path
  Error: 4-05 06:46:06] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/javascript/tools/autobuild.sh])
  A fatal error occurred: Exit status 1 from command: [/opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/javascript/tools/autobuild.sh]
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/codeql' failed with exit code 2
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/codeql' failed with exit code 2
      at toolrunnerErrorCatcher (/home/runner/work/_actions/github/codeql-action/4c1021c5041fca6023824e45efb[7](https://github.com/renovatebot/renovate/runs/5828906475?check_suite_focus=true#step:5:7)f[8](https://github.com/renovatebot/renovate/runs/5828906475?check_suite_focus=true#step:5:8)3178d52fe2/lib/toolrunner-error-catcher.js:86:1[9](https://github.com/renovatebot/renovate/runs/5828906475?check_suite_focus=true#step:5:9))
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Object.extractScannedLanguage (/home/runner/work/_actions/github/codeql-action/4c[10](https://github.com/renovatebot/renovate/runs/5828906475?check_suite_focus=true#step:5:10)21c5041fca6023824e45efb7f83178d52fe2/lib/codeql.js:544:13)
      at async createdDBForScannedLanguages (/home/runner/work/_actions/github/codeql-action/4c1021c5041fca6023824e45efb7f83178d52fe2/lib/analyze.js:79:13)
      at async finalizeDatabaseCreation (/home/runner/work/_actions/github/codeql-action/4c1021c5041fca6023824e45efb7f83178d52fe2/lib/analyze.js:96:5)
      at async runFinalize (/home/runner/work/_actions/github/codeql-action/4c1021c5041fca6023824e45efb7f83178d52fe2/lib/analyze.js:260:5)
      at async run (/home/runner/work/_actions/github/codeql-action/4c1021c5041fca6023824e45efb7f83178d52fe2/lib/analyze-action.js:78:9)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/4c1021c5041fca6023824e45efb7f83178d52fe2/lib/analyze-action.js:2[12](https://github.com/renovatebot/renovate/runs/5828906475?check_suite_focus=true#step:5:12):9)

https://github.com/renovatebot/renovate/runs/5828906475?check_suite_focus=true
```

**Comment by viceice** [comment]
Probably related to our custom config file

```yaml
paths-ignore:
  - '**/__fixtures__/'
  - /opt/hostedtoolcache
```

https://github.com/renovatebot/renovate/blob/493fd759de82d87745e329dcdfa8eb215d3cf546/.github/codeql/codeql-config.yml#L1-L4

**Comment by edoardopirovano** [comment]
Greetings, thanks for raising this with us. It looks like we accidentally made a change that broke your workflow - our apologies for that! We've now reverted that change so I'm hopeful that things should be working again for you. Would you mind trying your workflow again and letting is know if it's working now? Many thanks!
