### ISSUE TITLE
Error: Not Found RequestError [HttpError]: Not Found     at /home/runner/work/_actions/github/codeql-action/v1/node_modules/@octokit/request/dist-node/index.js:66:23

### ISSUE THREAD

**Issue by AncientSwordRage** [github/codeql-action#1023]
I'm getting this error from codeql

https://pipelines.actions.githubusercontent.com/serviceHosts/956685ef-aca5-407c-8d6e-14e1c815d4a1/_apis/pipelines/1/runs/27/signedlogcontent/2?urlExpires=2022-04-07T08%3A14%3A16.7919497Z&urlSigningMethod=HMACV1&urlSignature=bL1RBXYZgfUS1uBEyrEeJ46sjis9ze0cd3Y%2FwWYL9I8%3D

I don't understand it though, and I can't find an existing question on it anywhere. How can I resolve this?

**Comment by AncientSwordRage** [comment]
```
Run github/codeql-action/init@v1
  with:
    languages: javascript
    token: ***
    matrix: {
    "language": "javascript"
  }
    setup-python-dependencies: true
    debug: false
Error: Not Found
RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/github/codeql-action/v1/node_modules/@octokit/request/dist-node/index.js:66:[2](https://github.com/AncientSwordRage/ponder/runs/5861287760?check_suite_focus=true#step:3:2)[3](https://github.com/AncientSwordRage/ponder/runs/5861287760?check_suite_focus=true#step:3:3)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Job.doExecute (/home/runner/work/_actions/github/codeql-action/v1/node_modules/bottleneck/light.js:[4](https://github.com/AncientSwordRage/ponder/runs/5861287760?check_suite_focus=true#step:3:4)0[5](https://github.com/AncientSwordRage/ponder/runs/5861287760?check_suite_focus=true#step:3:5):18) {
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 07 Apr 2022 02:00:48 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=3153[6](https://github.com/AncientSwordRage/ponder/runs/5861287760?check_suite_focus=true#step:3:6)000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '04C3:39F2:63B4DA:11A8125:624E45D0',
    'x-ratelimit-limit': '1000',
    'x-ratelimit-remaining': '998',
    'x-ratelimit-reset': '1649300448',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '2',
    'x-xss-protection': '0'
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/AncientSwordRage/ponder/actions/runs/2106169[7](https://github.com/AncientSwordRage/ponder/runs/5861287760?check_suite_focus=true#step:3:7)60',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'CodeQL-Action/1.1.7 octokit-core.js/3.1.2 Node.js/12.22.7 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { agent: [Agent], hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest/reference/actions#get-a-workflow-run'
}
Error: init action failed: HttpError: Not Found
RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/github/codeql-action/v1/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Job.doExecute (/home/runner/work/_actions/github/codeql-action/v1/node_modules/bottleneck/light.js:405:1[8](https://github.com/AncientSwordRage/ponder/runs/5861287760?check_suite_focus=true#step:3:8)) {
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 07 Apr 2022 02:00:48 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '04C4:4B18:5D1D83:1187D[9](https://github.com/AncientSwordRage/ponder/runs/5861287760?check_suite_focus=true#step:3:9)9:624E45D0',
    'x-ratelimit-limit': '[10](https://github.com/AncientSwordRage/ponder/runs/5861287760?check_suite_focus=true#step:3:10)00',
    'x-ratelimit-remaining': '997',
    'x-ratelimit-reset': '1649300448',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '3',
    'x-xss-protection': '0'
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/AncientSwordRage/ponder/actions/runs/2106169760',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'CodeQL-Action/1.1.7 octokit-core.js/3.1.2 Node.js/[12](https://github.com/AncientSwordRage/ponder/runs/5861287760?check_suite_focus=true#step:3:12).[22](https://github.com/AncientSwordRage/ponder/runs/5861287760?check_suite_focus=true#step:3:22).7 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { agent: [Agent], hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest/reference/actions#get-a-workflow-run'
}
0s
0s
0s
0s
```

**Comment by aeisenberg** [comment]
Thank you for posting. I am unsure exactly why there was a 404 error here. When I try to access that failing endpoint I can successfully retrieve the workflow run:

```
curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/AncientSwordRage/ponder/actions/runs/2106169760
```

It looks like your repo has not had any issues prior to this run. So, it's possible there was a problem with GitHub Actions and it was unable to find the workflow run temporarily.

Please let me know if you continue to see this error.

**Comment by kostya-luxuryescape** [comment]
We started getting exact same problems with our repos!

**Comment by dtcMLOps** [comment]
Greetings guys, I am getting the same error:

![Screenshot from 2022-10-20 11-10-12](https://user-images.githubusercontent.com/115469901/197001756-cfe61e9c-e786-4af5-912b-da9e00f0eebc.png)

**Comment by aeisenberg** [comment]
@dtcMLOps Is your repository public? If not, and you want to use code scanning, you need to enable advanced security on that repository and I believe there is a cost for that.

**Comment by dtcMLOps** [comment]
Hi @aeisenberg indeed, my repository is private and within an organization. Probably that is the error I am getting.

**Comment by aeisenberg** [comment]
Thanks for responding. I'll close this issue and if you or anyone else continues to have a problem, please create a new one.
