### ISSUE TITLE
Codeql action keeps crashing

### ISSUE THREAD

**Issue by AMS21** [github/codeql-action#1082]
I am using the codeql-action to analyse my C++ project. But the action keeps crashing no clue why.

sample log:
```
  /opt/hostedtoolcache/CodeQL/0.0.0-20220428/x64/codeql/codeql database run-queries --ram=5922 --threads=2 /home/runner/work/_temp/codeql_databases/cpp --min-disk-free=1024 -v /home/runner/work/_temp/codeql_databases/cpp-queries-builtin.qls
  Writing logs to /home/runner/work/_temp/codeql_databases/cpp/log/database-run-queries-20220523.083639.146.log.
  Writing logs to /home/runner/work/_temp/codeql_databases/cpp/log/execute-queries-20220523.083639.790.log.
  Compiling in one thread due to RAM limits.
  (...)
  Starting evaluation of codeql/cpp-queries/Likely Bugs/Arithmetic/SignedOverflowCheck.ql.
  A fatal error occurred: RelationManager failed to produce already COMPUTEDTranslatedStmt::TranslatedLoop::getFirstConditionInstruction#dispred#f0820431#bf/2@4e5d10wh
  Error: Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20220428/x64/codeql/codeql with arguments database,run-queries,--ram=5922,--threads=2,/home/runner/work/_temp/codeql_databases/cpp,--min-disk-free=1024,-v,/home/runner/work/_temp/codeql_databases/cpp-queries-builtin.qls.
  
        Exit code 2 and error was:
  
        Writing logs to /home/runner/work/_temp/codeql_databases/cpp/log/database-run-queries-20220523.083639.146.log.
  Writing logs to /home/runner/work/_temp/codeql_databases/cpp/log/execute-queries-20220523.083639.790.log.
  (...)
  Compiling query plan for /opt/hostedtoolcache/CodeQL/0.0.0-20220428/x64/codeql/qlpacks/codeql/cpp-queries/0.1.1/Security/CWE/CWE-327/BrokenCryptoAlgorithm.ql.
  Resolving imports for /opt/hostedtoolcache/CodeQL/0.0.0-20220428/x64/codeql/qlpacks/codeql/cpp-quer
  Error: Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20220428/x64/codeql/codeql with arguments database,run-queries,--ram=5922,--threads=2,/home/runner/work/_temp/codeql_databases/cpp,--min-disk-free=1024,-v,/home/runner/work/_temp/codeql_databases/cpp-queries-builtin.qls.
  
        Exit code 2 and error was:
  
        Writing logs to /home/runner/work/_temp/codeql_databases/cpp/log/database-run-queries-20220523.083639.146.log.
  Writing logs to /home/runner/work/_temp/codeql_databases/cpp/log/execute-queries-20220523.083639.790.log.
  (...)
  Compiling query plan for /opt/hostedtoolcache/CodeQL/0.0.0-20220428/x64/codeql/qlpacks/codeql/cpp-queries/0.1.1/Security/CWE/CWE-327/BrokenCryptoAlgorithm.ql.
  Resolving imports for /opt/hostedtoolcache/CodeQL/0.0.0-20220428/x64/codeql/qlpacks/codeql/cpp-quer
      at runTool (/home/runner/work/_actions/github/codeql-action/v2/lib/codeql.js:780:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.databaseRunQueries (/home/runner/work/_actions/github/codeql-action/v2/lib/codeql.js:598:13)
      at async runQueryGroup (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze.js:216:9)
      at async runQueries (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze.js:149:38)
      at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze-action.js:81:24)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze-action.js:217:9)
  Error: Error running analysis for cpp: Error: Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20220428/x64/codeql/codeql with arguments database,run-queries,--ram=5922,--threads=2,/home/runner/work/_temp/codeql_databases/cpp,--min-disk-free=1024,-v,/home/runner/work/_temp/codeql_databases/cpp-queries-builtin.qls.
  
        Exit code 2 and error was:
  
        Writing logs to /home/runner/work/_temp/codeql_databases/cpp/log/database-run-queries-20220523.083639.146.log.
  (...)
  Compiling query plan for /opt/hostedtoolcache/CodeQL/0.0.0-20220428/x64/codeql/qlpacks/codeql/cpp-queries/0.1.1/Security/CWE/CWE-327/BrokenCryptoAlgorithm.ql.
  Resolving imports for /opt/hostedtoolcache/CodeQL/0.0.0-20220428/x64/codeql/qlpacks/codeql/cpp-quer
  CodeQLAnalysisError: Error running analysis for cpp: Error: Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20220428/x64/codeql/codeql with arguments database,run-queries,--ram=5922,--threads=2,/home/runner/work/_temp/codeql_databases/cpp,--min-disk-free=1024,-v,/home/runner/work/_temp/codeql_databases/cpp-queries-builtin.qls.
  
        Exit code 2 and error was:
  
        Writing logs to /home/runner/work/_temp/codeql_databases/cpp/log/database-run-queries-20220523.083639.146.log.
  (...)
  Compiling query plan for /opt/hostedtoolcache/CodeQL/0.0.0-20220428/x64/codeql/qlpacks/codeql/cpp-queries/0.1.1/Security/CWE/CWE-327/BrokenCryptoAlgorithm.ql.
  Resolving imports for /opt/hostedtoolcache/CodeQL/0.0.0-20220428/x64/codeql/qlpacks/codeql/cpp-quer
      at runQueries (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze.js:191:19)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze-action.js:81:24)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze-action.js:217:9) {
    queriesStatusReport: { analyze_failure_language: 'cpp' }
  }
```

[full log](https://github.com/AMS21/Phi/runs/6544023186)

**Comment by edoardopirovano** [comment]
Greetings, thanks for reaching out to us with this issue. Digging a bit further in the logs reveals some errors such as:

```
  [8/46 eval 32m5s] Query failed: codeql/cpp-queries/Critical/NewFreeMismatch.ql (Query evaluation ran out of Java heap (Java heap maximum: 1777 MiB, Off-heap arrays maximum: 2961 MiB).
  (eventual cause: OutOfMemoryError "Java heap space")).
```

These errors typically indicate that your project is too large for CodeQL to analyse with the amount of RAM found on the default GitHub runners. You can tweak the way we allocate memory to _possibly_ make the workflow succeed by adding the following environment variable to your CodeQL job (for example, just below the `runs-on` field):

```
    env:
      CODEQL_ACTION_EXTRA_OPTIONS: '{"database": {"run-queries": ["--off-heap-ram=0"]}}'
```

This forces us to allocate all our memory via the JVM as opposed to splitting the available memory into two pools, and may therefore help your workflow pass. However, even with this setting the memory pressure will be very large because your code base is seemingly just too large for us to analyze. This may result in your workflow running very slowly, and potentially hitting a timeout.

A better solution, if possible, would be to only analyze a smaller build target. For example, if you have dependencies that you are not interested in seeing alerts for you could build these before the `init` step of the workflow to make sure they don't end up in the CodeQL database. Also, I would recommend skipping any test code in the build target that you get CodeQL to analyze. This will make the database smaller and therefore easier to analyze.

If this is not an option and you really do need to analyze all the code, and the above workaround does not result in acceptable performance, then my next suggestion would be to set up a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) for your project with more RAM than the default GitHub ones. I appreciate this is a time-consuming and expensive step, so may not be feasible.

**Comment by AMS21** [comment]
Ah yes, I was also analyzing all the my unit tests which obviously isn't such a good idea. Thanks for taking the time to analyze the issue here.

But it would probably be help full in the future if the action would give some form of error message instead of just saying `Exit code 2`. In case somebody runs into a similar issue in the future.

Closing as my issue has been resolved.
