### ISSUE TITLE
fatal: unsafe repository is owned by someone else

### ISSUE THREAD

**Issue by xvitaly** [github/codeql-action#1113]
Fatal error when running CodeQL action:
```
ERROR: ld.so: object '/__t/CodeQL/0.0.0-20220527/x64/codeql/tools/linux64/${LIB}_${PLATFORM}_trace.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
fatal: unsafe repository ('/__w/tuned-switcher/tuned-switcher' is owned by someone else)
To add an exception for this directory, call:
	git config --global --add safe.directory /__w/tuned-switcher/tuned-switcher
Failed to call git to get current commit. Continuing with data from environment or input: Error: The process '/usr/bin/git' failed with exit code 128
Error: The process '/usr/bin/git' failed with exit code 128
    at ExecState._setResult (/__w/_actions/github/codeql-action/v2/node_modules/@actions/exec/lib/toolrunner.js:592:25)
    at ExecState.CheckComplete (/__w/_actions/github/codeql-action/v2/node_modules/@actions/exec/lib/toolrunner.js:575:18)
    at ChildProcess.<anonymous> (/__w/_actions/github/codeql-action/v2/node_modules/@actions/exec/lib/toolrunner.js:469:27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12)
```
Action file: [codeql.yml](https://github.com/EasyCoding/tuned-switcher/blob/master/.github/workflows/codeql.yml)
Log: https://github.com/EasyCoding/tuned-switcher/runs/6999707909

**Comment by aibaars** [comment]
The first error message is harmless: `ERROR: ld.so: object '/__t/CodeQL/0.0.0-20220527/x64/codeql/tools/linux64/${LIB}_${PLATFORM}_trace.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored. 
`
CodeQL uses LD_PRELOAD to intercept any compiler invocations. The value is set by the `codeql-action/init` step which is executed in the docker container. As a result the environment variable refers to the file path of the CodeQL tracing library in the container. The environment variable is "inherited" by subsequent steps. For example the `codeql-action/autobuild` step has an `env:` entry like: `LD_PRELOAD: /__t/CodeQL/0.0.0-20220527/x64/codeql/tools/linux64/${LIB}_${PLATFORM}_trace.so` . This makes it possible for CodeQL to "see" any compiler calls in the container that occur during the build. However, the LD_PRELOAD variable is also set for the `docker exec` command. This command runs outside the container, and outside the container the path `/__t/CodeQL/0.0.0-20220527/x64/codeql/tools/linux64/${LIB}_${PLATFORM}_trace.so` is invalid. This causes `ld` to complain. This is harmless because CodeQL has no need for tracing the `docker exec` command. 

I'm a bit surprised by the `git` related error, because the `git config --global --add safe.directory /__w/tuned-switcher/tuned-switcher` command was run as part of the `actions/checkout` step. The use of `git` by the `codeql-action` is not essential. It is used to figure out the commit SHA of the analyzed code. If the command fails the `codeql-action` defaults to using the `GITHUB_SHA` environment variable which in normal cases contains the right value .

**Comment by tristan957** [comment]
@aibaars I am seeing the git failure mentioned in this issue.

```
fatal: detected dubious ownership in repository at '/__w/hse/hse'
To add an exception for this directory, call:

	git config --global --add safe.directory /__w/hse/hse
Failed to call git to get current commit. Continuing with data from environment or input: Error: The process '/usr/bin/git' failed with exit code 128
Error: The process '/usr/bin/git' failed with exit code 128
    at ExecState._setResult (/__w/_actions/github/codeql-action/v2/node_modules/@actions/exec/lib/toolrunner.js:592:25)
    at ExecState.CheckComplete (/__w/_actions/github/codeql-action/v2/node_modules/@actions/exec/lib/toolrunner.js:575:18)
    at ChildProcess.<anonymous> (/__w/_actions/github/codeql-action/v2/node_modules/@actions/exec/lib/toolrunner.js:469:27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:6[87](https://github.com/hse-project/hse/runs/7760117965?check_suite_focus=true#step:8:88):12)
```

https://github.com/hse-project/hse/runs/7760117965?check_suite_focus=true

But you can see that I am setting that up during  the checkout at https://github.com/hse-project/hse/pull/354/files#diff-ec82a1210eee62532fa878b35c0defd6db76f03a97579afabe79a90588d72165R41.

**Comment by aibaars** [comment]
Most likely the user ID in the Docker container is different from the user ID of the owner of the repository folder. I think the error message can be ignored though because the codeql-action falls back on using the GITHUB_SHA environment variable instead .

**Comment by tristan957** [comment]
FWIW I think this is the upstream issue: https://github.com/actions/runner/issues/2033
