### ISSUE TITLE
Do not let the upload action fail if the SARIF file does not contain a location.

### ISSUE THREAD

**Issue by aetos382** [github/codeql-action#1738]
When I compiled my C# project with the `ErrorLog` option, the compiler generated the following SARIF file.

<details>
<summary>SARIF File</summary>

```json

{
  "$schema": "http://json.schemastore.org/sarif-2.1.0",
  "version": "2.1.0",
  "runs": [
    {
      "results": [
        {
          "ruleId": "EnableGenerateDocumentationFile",
          "ruleIndex": 291,
          "level": "warning",
          "message": {
            "text": "Set MSBuild property 'GenerateDocumentationFile' to 'true' in project file to enable IDE0005 (Remove unnecessary usings/imports) on build"
          },
          "properties": {
            "warningLevel": 1
          }
        }
      ],
      "tool": {
        "driver": {
          "name": "Microsoft (R) Visual C# Compiler",
          "version": "4.7.0-3.23280.5 (aff92b57)",
          "dottedQuadFileVersion": "4.7.0.0",
          "semanticVersion": "4.7.0",
          "language": "en-US",
          "rules": [
           // Too long to be omitted.
          ]
        }
      },
      "columnKind": "utf16CodeUnits"
    }
  ]
}

```

</details>

Uploading this file using the `upload-sarif` action will result in the following error.

```
Error: Code Scanning could not process the submitted SARIF file:
locationFromSarifResult: expected at least one location
    at Object.waitForProcessing (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:337:23)
    at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:55:13)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:70:9)
```

The reason this file did not contain a `location` element is because there was no warning associated with the location in the source file, and the SARIF file is not malformed.
To avoid interrupting the workflow when uploading such a file, do not make an error with this file.

Note that I know that this error is generated by the GitHub API, not the `upload-sarif` action.
So, I think it might be more appropriate to fix the API behavior or add an option to the API to ignore the error.
If so, please forward this issue to the appropriate department.

**Comment by aeisenberg** [comment]
I'm closing this issue, but feel free to continue the discussion if you have any more questions.

**Comment by edwardgalligan** [comment]
> they mentioned that it is part of the core design that all alerts have at least one location

It would be great to get a justification from the team on this "core design" decision.

As it stands, it means lossy pre-processing of SARIF files that contain artifacts with uris the Github API SARIF parser doesn't understand (e.g. https uris supported by the SARIF spec)

**Comment by toadslop** [comment]
I think those who believe that a location must be required have failed to consider the possibility that someone might want to upload an SBOM scan. An SBOM scan might have a logical location pointing to a package name, but it absolutely will not and cannot have a physical location, and yet github requires a physical location to be present.
