### ISSUE TITLE
Analysis upload fails with "rejecting SARIF, as there are more runs than allowed"

### ISSUE THREAD

**Issue by ben-manes** [github/codeql-action#2000]
```console
Run github/codeql-action/upload-sarif@cdcdbb57970684[1](https://github.com/ben-manes/caffeine/actions/runs/6915822206/job/18815190960#step:7:1)c47f7063dda365e292e5cad7a
Uploading results
Waiting for processing to finish
Error: Code Scanning could not process the submitted SARIF file:
rejecting SARIF, as there are more runs than allowed (21 > 20)
Error: Code Scanning could not process the submitted SARIF file:
rejecting SARIF, as there are more runs than allowed (21 > 20)
    at Object.waitForProcessing (/home/runner/work/_actions/github/codeql-action/cdcdbb579706841c47f7063dda365e292e5cad7a/lib/upload-lib.js:337:23)
    at async run (/home/runner/work/_actions/github/codeql-action/cdcdbb579706841c47f7063dda365e292e5cad7a/lib/upload-sarif-action.js:55:13)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/cdcdbb579706841c47f7063dda365e292e5cad7a/lib/upload-sarif-action.js:70:9)
```
See the [github-actions log](https://github.com/ben-manes/caffeine/actions/runs/6915822206/job/18815190960).

At best maybe this refers to the total build using multiple actions and a matrix, so it does get throttled by the 20 concurrent jobs limit for the free tier. I don't see why that should have any impact here and should be a limit on the action scheduling and not the submission.

**Comment by ben-manes** [comment]
and it failed even when I reran it as the only active job. I am not sure what this error is referring to.

**Comment by ben-manes** [comment]
Looks like it’s documented so I think this is the analyzer’s fault.
