### ISSUE TITLE
Analyze (javascript-typescript) failing when reviewing legacy node 10 applications

### ISSUE THREAD

**Issue by dave-schmitz1** [github/codeql-action#2182]
We are currently trying to enable CodeQL for many of our repositories and recently ran into problems with some older Angular applications built with Node 10. The applications are built with the following versions:

Angular: 7.1.2
Typescript: 3.1.6
Node: 10.24.1

Sample Log
```
[2024-03-01 09:51:00] [build-stdout] Found Node.js at: node
[2024-03-01 09:51:00] [build-stdout] Found Node.js version: v10.24.1
[2024-03-01 09:51:00] [build-stdout] Opening project /home/docker/actions-runner/_work/wfm-sw-application/wfm-sw-application/Applications/Web Portal/_Source/Areas/DeviceStatus/tsconfig.json
[2024-03-01 09:51:00] [build-stdout] Memory for TypeScript process: 3000 MB, and 400 MB reserve
[2024-03-01 09:51:00] [build-stderr] /home/docker/actions-runner/_work/_tool/CodeQL/2.16.3/x64/codeql/javascript/tools/typescript-parser-wrapper/node_modules/typescript/lib/typescript.js:139
[2024-03-01 09:51:00] [build-stderr]     for (let i = startIndex ?? 0; i < array.length; i++) {
[2024-03-01 09:51:00] [build-stderr]                              ^
[2024-03-01 09:51:00] [build-stderr] SyntaxError: Unexpected token ?
[2024-03-01 09:51:00] [build-stderr]     at Module._compile (internal/modules/cjs/loader.js:723:23)
[2024-03-01 09:51:00] [build-stderr]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[2024-03-01 09:51:00] [build-stderr]     at Module.load (internal/modules/cjs/loader.js:653:32)
[2024-03-01 09:51:00] [build-stderr]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[2024-03-01 09:51:00] [build-stderr]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[2024-03-01 09:51:00] [build-stderr]     at Module.require (internal/modules/cjs/loader.js:692:17)
[2024-03-01 09:51:00] [build-stderr]     at require (internal/modules/cjs/helpers.js:25:18)
[2024-03-01 09:51:00] [build-stderr]     at Object.<anonymous> (/home/docker/actions-runner/_work/_tool/CodeQL/2.16.3/x64/codeql/javascript/tools/typescript-parser-wrapper/typescript.js:6:22)
[2024-03-01 09:51:00] [build-stderr]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[2024-03-01 09:51:00] [build-stderr]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[2024-03-01 09:51:00] [build-stderr] com.semmle.util.exception.CatastrophicError: The TypeScript parser wrapper crashed with exit code 1
[2024-03-01 09:51:00] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.getExceptionFromMalformedResponse(TypeScriptParser.java:399)
[2024-03-01 09:51:00] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.talkToParserWrapper(TypeScriptParser.java:364)
[2024-03-01 09:51:00] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.loadMetadata(TypeScriptParser.java:416)
[2024-03-01 09:51:00] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.setupParserWrapper(TypeScriptParser.java:320)
[2024-03-01 09:51:00] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.talkToParserWrapper(TypeScriptParser.java:351)
[2024-03-01 09:51:00] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.openProject(TypeScriptParser.java:514)
[2024-03-01 09:51:00] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.extractTypeScript(AutoBuild.java:1037)
[2024-03-01 09:51:00] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.extractSource(AutoBuild.java:755)
[2024-03-01 09:51:00] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.run(AutoBuild.java:462)
[2024-03-01 09:51:00] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.main(AutoBuild.java:1352)
Error: 3-01 09:51:00] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/home/docker/actions-runner/_work/_tool/CodeQL/2.16.3/x64/codeql/javascript/tools/autobuild.sh])
A fatal error occurred: Exit status 1 from command: [/home/docker/actions-runner/_work/_tool/CodeQL/2.16.3/x64/codeql/javascript/tools/autobuild.sh]
Error: Encountered a fatal error while running "/home/docker/actions-runner/_work/_tool/CodeQL/2.16.3/x64/codeql/codeql database trace-command --index-traceless-dbs /home/docker/actions-runner/_work/_temp/codeql_databases/javascript". Exit code was 2 and error was: A fatal error occurred: Exit status 1 from command: [/home/docker/actions-runner/_work/_tool/CodeQL/2.16.3/x64/codeql/javascript/tools/autobuild.sh]. See the logs for more details.
```

I could not find anywhere in the documentation where it says older versions are not supported but the character is said was not supported does not appear to be supported until Node 14. Is there something I can do in the meantime to get CodeQL to work with these older applications?

**Comment by mbg** [comment]
Hi @dave-schmitz1 👋 

Thank you for bringing this to our attention. I have passed this on to our JavaScript team and will get back to you once I have an update from them.

**Comment by aibaars** [comment]
As far as I know CodeQL can analyze older Javascript code, however, the CodeQL analyzer runs the typescript compiler which requires a relatively recent version of nodejs to run. 

Have you tried installing a more recent version of nodejs? CodeQL doesn't build or run your Javascript code, so it doesn't really matter what version of nodejs your application is made for.

**Comment by dave-schmitz1** [comment]
@aibaars for the repository that we are adding CodeQL we have two different sets of Angular apps, first a set that currently uses Node 18 which works as expected and secondly a set of older legacy apps that use Node 10 to build which this is failing on. The current process installs the node version, builds the application, and then runs CodeQL. Are you suggesting installing a newer version of Node after the compile process has been completed?

**Comment by aibaars** [comment]
There is no need to build the project before running CodeQL. If you really
want to run both the build and the CodeQL analysis in the same job then
installing a newer version of node before running CodeQL should work.

**Comment by dave-schmitz1** [comment]
@aibaars is it not needed to compile the application prior to CodeQL scanning just because of it being in javascript - typescript language or does this apply for other languages as well? We did see CodeQL offers an 'auto-build' option but decided to customize our own build operation after initialize and before analyze. While this is rather quick process for our angular applications the building process is rather lengthy for some of our c sharp code.

**Comment by aeisenberg** [comment]
As @aibaars says, it is not necessary to run a build for javascript or typescript. The extractor for these languages can work without any explicit build. So, there should be no need to install node 10 in the actions runner.

Other languages, like java, C#, C++, and go do require builds in order for extraction to work.

Is there a particular reason why you want to run the build?

**Comment by dave-schmitz1** [comment]
Not particularly other than I was under the impression that I thought I would have to do similar workflow process of build and was re-using the workflow for CodeQL. We currently run this on a self-hosted runner that does not have Node installed by default so the process does the following prior to building: 

1. Installs version of node required for build
2. Obtains credentials for private npm feed
3. Installs dependencies

Being newer to implementing CodeQL, we made the assumption these same steps along with building would be needed for analyze process.

**Comment by aeisenberg** [comment]
I can understand your confusion since your repository does build the code, but this is not necessary for codeql analysis. For javascript and typescript, you do not need to install npm dependencies and you do not need to run a build, transpiler, minification, or compilation. CodeQL operates directly on the raw javascript and typescript. I hope this clarifies things.

**Comment by theveriton** [comment]
I also had the same issue in our org, for one build nvm had switched to v11 of node on the self-hosted server, I switched it back to v18 and it started working...this used to work with both node versions before though, because nvm often switched back to v11 and yesterday was the first time CodeQL errored out because of that.

**Comment by dave-schmitz1** [comment]
Thank you for your help on this @aibaars and @aeisenberg. I have since switch this to only analyze using the latest version of node and that seems to work for these legacy applications.
