### ISSUE TITLE
Error: Not Found on Initialize step

### ISSUE THREAD

**Issue by dwisiswant0** [github/codeql-action#246]
After I read issue #142 I tried to run this action using my personal token on my private repository organization, but still got error as:

```
Error: Not Found
RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/github/codeql-action/v1/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Job.doExecute (/home/runner/work/_actions/github/codeql-action/v1/node_modules/bottleneck/light.js:405:18) {
  name: 'HttpError',
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Mon, 05 Oct 2020 02:59:24 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '404 Not Found',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-oauth-scopes': 'repo',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '0402:530B:1401D34:31545C0:5F7A8C0C',
    'x-oauth-scopes': 'repo',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4997',
    'x-ratelimit-reset': '1601870364',
    'x-ratelimit-used': '3',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'PUT',
    url: 'https://api.github.com/repos/kitabisa/teler/code-scanning/analysis/status',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'CodeQL Action octokit-core.js/3.1.2 Node.js/12.13.1 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"workflow_run_id":288623508,"workflow_name":"Review","job_name":"review","analysis_key":".github/workflows/review.yaml:review","commit_oid":"db31b57d5d83d0b39bd24c83cbe677b9fca3c4c1","ref":"refs/heads/development","action_name":"init","action_oid":"unknown","started_at":"2020-10-05T02:59:24.205Z","action_started_at":"2020-10-05T02:59:24.205Z","status":"starting","matrix_vars":"null"}',
    request: { agent: [Agent], hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest'
}
```

And,

```
Error: init action failed: HttpError: Not Found
RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/github/codeql-action/v1/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Job.doExecute (/home/runner/work/_actions/github/codeql-action/v1/node_modules/bottleneck/light.js:405:18) {
  name: 'HttpError',
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Mon, 05 Oct 2020 02:59:24 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '404 Not Found',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-oauth-scopes': 'repo',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '0403:5EEA:1302790:2E061BE:5F7A8C0C',
    'x-oauth-scopes': 'repo',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4996',
    'x-ratelimit-reset': '1601870364',
    'x-ratelimit-used': '4',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'PUT',
    url: 'https://api.github.com/repos/kitabisa/teler/code-scanning/analysis/status',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'CodeQL Action octokit-core.js/3.1.2 Node.js/12.13.1 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"workflow_run_id":288623508,"workflow_name":"Review","job_name":"review","analysis_key":".github/workflows/review.yaml:review","commit_oid":"db31b57d5d83d0b39bd24c83cbe677b9fca3c4c1","ref":"refs/heads/development","action_name":"init","action_oid":"unknown","started_at":"2020-10-05T02:59:24.205Z","action_started_at":"2020-10-05T02:59:24.205Z","status":"aborted","cause":"Not Found","completed_at":"2020-10-05T02:59:24.617Z","matrix_vars":"null"}',
    request: { agent: [Agent], hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest'
}
```

What extra steps do I need to take to get this action right?

Thanks.

**Comment by robertbrignull** [comment]
Code scanning is only free to use on public repositories. To use on a private repository you'll need to contact the sales team. See https://resources.github.com/code-scanning/ for more info.

Closing this issue preemtively. If the above was not the issue feel free to reopen.
