### ISSUE TITLE
No such property: maven.mainClass / Java/Maven build failures 

### ISSUE THREAD

**Issue by ottlinger** [github/codeql-action#2657]
Recently I experience build failures while running the codeql-java-autobuild:

```
  [2024-12-18 05:24:27] [autobuild] > /home/runner/work/mailclena/mailclena/./mvnw clean package -f pom.xml -B -V -e -Dfindbugs.skip -Dcheckstyle.skip -Dpmd.skip=true -Dspotbugs.skip -Denforcer.skip -Dmaven.javadoc.skip -DskipTests -Dmaven.test.skip.exec -Dlicense.skip=true -Drat.skip=true -Dspotless.check.skip=true -s /home/runner/.m2/settings.xml -t /home/runner/.m2/toolchains.xml
  [2024-12-18 05:24:27] [autobuild] Picked up JAVA_TOOL_OPTIONS:  -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
  [2024-12-18 05:24:28] [autobuild] org.codehaus.plexus.classworlds.launcher.ConfigurationException: No such property: maven.mainClass
  [2024-12-18 05:24:28] [autobuild] 	at org.codehaus.plexus.classworlds.launcher.ConfigurationParser.filter(ConfigurationParser.java:355)
  [2024-12-18 05:24:28] [autobuild] 	at org.codehaus.plexus.classworlds.launcher.ConfigurationParser.parse(ConfigurationParser.java:114)
  [2024-12-18 05:24:28] [autobuild] 	at 
```

on project https://github.com/ottlinger/mailclena

As I do not configure any of the variables in 
https://github.com/ottlinger/mailclena/blob/master/.github/workflows/codeql.yml
I wonder how to proceed.

Thanks

**Comment by aeisenberg** [comment]
It looks like your codeql scans started failing on this commit: https://github.com/ottlinger/mailclena/actions/runs/11750645752 where you upgraded to mvn 4-beta-5. 

In your codeql workflow you are using `autobuild`, which uses heuristics to try to build a project using standard build commands. I'm guessing that autobuild is trying to use an incorrect maven command.

The easiest thing to do is to use [`build-mode: none`](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages#about-build-mode-none-for-codeql). It is a small change to your workflow.

**Comment by ottlinger** [comment]
I assume the problem is somewhere in the autobuild script as it adds an unknown property:

`  [2024-12-18 05:24:28] [autobuild] org.codehaus.plexus.classworlds.launcher.ConfigurationException: No such property: maven.mainClass
`

The build is back in the green via https://github.com/ottlinger/mailclena/commit/1d8dc079937fd360c8374afe982742e6f6f9b44f but I assume that is not what you intended. 

Thanks

**Comment by aeisenberg** [comment]
That's another option. You're using an explicit build command. If that works for your repository, then there are no problems. I'll close this issue.

**Comment by ottlinger** [comment]
I thought that you would include something on your side to not issue this parameter by default in Maven builds as it is incompatible with newer Maven versions .... but I'm fine if my build is back in the green :) Thanks again.

**Comment by aeisenberg** [comment]
I'll discuss this with the team maintaining the Java extractor.
