### ISSUE TITLE
Do not crash with empty folder

### ISSUE THREAD

**Issue by prabhu** [github/codeql-action#282]
Scan uses upload-sarif step with a directory called reports. If this directory happens to be empty (no results produced), then the upload step is failing as below:

```
Error: No SARIF files found to upload in "reports".
Error: No SARIF files found to upload in "reports".
    at Object.upload (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:82:19)
    at run (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:29:46)
```

This is breaking quite a large number of builds. Is it possible to detect empty directories and prevent this step from failing with error? It is going to take some effort to make scan produce empty sarif file for various cases so would appreciate this workaround from you.

**Comment by strughle333** [comment]
ggggg
