### ISSUE TITLE
CodeQL-Runner CLI: Unexpected end of JSON input

### ISSUE THREAD

**Issue by sawp-d** [github/codeql-action#407]
I seem to be running into an issue with uploading sarif results generated from trivy where the GitHub Action for upload works as expected but reproducing the same command over the CLI doesn't seem to work. The same report.sarif file works in GH Actions. Could I be missing something with the command?

```
./codeql-runner-linux upload --sarif-file "report.sarif" --repository "user/repo" --commit "commit-hash" --ref "refs/heads/main" --github-url "https://github.com" --github-auth "personal-access-token"

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at validateSarifFileSchema (/snapshot/dist/codeql-runner.js)
    at uploadFiles (/snapshot/dist/codeql-runner.js)
    at Object.uploadFromRunner (/snapshot/dist/codeql-runner.js)
    at Command.<anonymous> (/snapshot/dist/codeql-runner.js)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:62:5)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1376:13)
    at internal/main/run_main_module.js:17:47
```

My PAT has full control for private repos (even though the repo is public) but it's not clear if any more permissions are needed? GitHub shows that the PAT has never been used. Does it need a different scope?

**Comment by sawpresto** [comment]
Update, looks like the SARIF file generated was empty :)

**Comment by sawp-d** [comment]
Looks like SARIF file was empty, resolved!
