### ISSUE TITLE
Temp mirror solution is getting out of sync

### ISSUE THREAD

**Issue by spaladugu91** [github/codeql-action#970]
Temp mirror solution is getting out of sync - have to stop and start to get it synced. Some time even restart wont work, So have to delete org and recreate

```
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /usr/share/rbenv/versions/2.7.1-bundler2/lib/ruby/2.7.0/net/http.rb:1009:in `connect'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /usr/share/rbenv/versions/2.7.1-bundler2/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /usr/share/rbenv/versions/2.7.1-bundler2/lib/ruby/2.7.0/net/http.rb:932:in `start'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /usr/share/rbenv/versions/2.7.1-bundler2/lib/ruby/2.7.0/net/http.rb:1483:in `request'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /github/vendor/gems/2.7.1/ruby/2.7.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:87:in `perform_request'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /github/vendor/gems/2.7.1/ruby/2.7.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:43:in `block in call'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /github/vendor/gems/2.7.1/ruby/2.7.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /github/vendor/gems/2.7.1/ruby/2.7.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:38:in `call'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /github/vendor/gems/2.7.1/ruby/2.7.0/gems/faraday-0.17.3/lib/faraday/request/url_encoded.rb:15:in `call'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /github/vendor/gems/2.7.1/ruby/2.7.0/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /github/vendor/gems/2.7.1/ruby/2.7.0/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /github/vendor/gems/2.7.1/ruby/2.7.0/gems/faraday-0.17.3/lib/faraday/connection.rb:175:in `post'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /github/lib/github/githooks/pre_receive_lfs_integrity.rb:111:in `query_unknown_oids'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /github/lib/github/githooks/pre_receive_lfs_integrity.rb:85:in `check'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /github/lib/github/githooks/push_context.rb:42:in `block (2 levels) in check'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /github/lib/github/config/stats.rb:185:in `time'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /github/lib/github/githooks/push_context.rb:41:in `block in check'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /github/lib/github/githooks/push_context.rb:36:in `each'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from /github/lib/github/githooks/push_context.rb:36:in `check'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from hooks/pre-receive.rb:38:in `<main>'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from hooks/pre-receive.rb:1:in `__ruby_concealer__'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: remote:         from hooks/pre-receive.rb:1:in `<main>'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: To https://githubmirror.tesla.cn/Factory-Software/MobileUI.git
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]:  ! [remote rejected]   develop -> develop (pre-receive hook declined)
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]:  ! [remote rejected]   r/2022.2.2 -> r/2022.2.2 (pre-receive hook declined)
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]:  ! [remote rejected]   fredev-login -> fredev-login (pre-receive hook declined)
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]:  ! [remote rejected]   r/2022.2.2.cn.1 -> r/2022.2.2.cn.1 (pre-receive hook declined)
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: error: failed to push some refs to 'https://githubmirror.tesla.cn/Factory-Software/MobileUI.git'
Mar 07 05:11:24 sjc04p1gites07-pod3-sjc04-tzla-net-replica ghes-mirror[6716]: [1B blob data]
```

**Comment by aeisenberg** [comment]
Can you add some context here? I am not sure how this is related to the codeql-action.
